export const episodeRoman = ["I", "II", "III", "IV", "V", "VI"]

export const episodeTrailer = [
    "https://www.youtube.com/embed/bD7bpG-zDJQ?si=IGi3EQSCefkoFUof",
    "https://www.youtube.com/embed/gYbW1F_c9eM?si=gS_dD8X62VgQe9Nf",
    "https://www.youtube.com/embed/5UnjrG_N8hU?si=_sdsNKO90JZ-atWM",
    "https://www.youtube.com/embed/vZ734NWnAHA?si=g4z38zdWYoYPcsQp",
    "https://www.youtube.com/embed/JNwNXF9Y6kY?si=8ohy5mzVNaIp-Pmt",
    "https://www.youtube.com/embed/p4vIFhk621Q?si=cuuvaZH3PSxtOE3d",
]

export const episodePoster = [
    "/episode1.jpg",
    "/episode2.jpg",
    "/episode3.jpg",
    "/episode4.jpg",
    "/episode5.jpg",
    "/episode6.jpg",
]

export const episodeBGPoster = [
    "/episode1bg.jpg",
    "/episode2bg.jpg",
    "/episode3bg.jpg",
    "/episode4bg.jpg",
    "/episode5bg.jpg",
    "/episode6bg.jpg",
]
export const starWarsCharacters = [
    "Luke Skywalker",
    "Leia Organa",
    "Han Solo",
    "Chewbacca",
    "Obi-Wan Kenobi",
    "Darth Vader",
    "Yoda",
    "R2-D2",
    "C-3PO",
    "Lando Calrissian",
    "Boba Fett",
    "Jabba the Hutt",
    "Emperor Palpatine",
    "Anakin Skywalker",
    "Padmé Amidala",
    "Qui-Gon Jinn",
    "Mace Windu",
    "Count Dooku",
    "General Grievous",
    "Jar Jar Binks",
    "Nute Gunray",
    "Asajj Ventress",
    "Darth Maul",
    "Jango Fett",
    "Boss Nass",
    "Wicket W. Warrick",
    "Rey",
    "Finn",
    "Poe Dameron",
    "Kylo Ren",
    "Supreme Leader Snoke",
    "Rose Tico",
    "General Hux",
    "Captain Phasma",
    "BB-8",
    "Maz Kanata",
    "Supreme Leader Snoke",
    "Ahsoka Tano",
    "Ezra Bridger",
    "Kanan Jarrus",
    "Hera Syndulla",
    "Sabine Wren",
    "Garazeb 'Zeb' Orrelios",
    "Din Djarin (The Mandalorian)",
    "Grogu (Baby Yoda)",
    "Bo-Katan Kryze",
    "Cad Bane",
    "Fennec Shand",
    "Boba Fett",
    "Andor Cassian",
    "Mon Mothma",
    "Thrawn",
    "Mara Jade",
    "Jaina Solo",
    "Jacen Solo",
    "Corran Horn",
    "Galen Marek (Starkiller)",
    "Grand Admiral Rae Sloane",
    "Zannah"
];